export const getUsers =async(req,res) =>{
    console.log("it works");
    try{

    }
    catch(err)
    {
        console.log(err);
        res.status(500).son({message:"Failed to get users"})
    }
}

export const getUser =async(req,res) =>{
    try{

    }
    catch(err)
    {
        console.log(err);
        res.status(500).son({message:"Failed to get user"})
    }
}

export const updateUser =async(req,res) =>{
    try{

    }
    catch(err)
    {
        console.log(err);
        res.status(500).son({message:"Failed to get user"})
    }
}

export const deleteUser =async(req,res) =>{
    try{

    }
    catch(err)
    {
        console.log(err);
        res.status(500).son({message:"Failed to get user"})
    }
}